### ISSUE TITLE
clean notebooks generator tool doesnt work

### ISSUE THREAD

**Issue by vramirez** [fastai/course22#26]
The tool tools/clean.py does not work. Seems like `read_nb` function is missing

**Comment by namra1** [comment]
need to modify clean.py file in tools directory:
import nbdev
...
nb = read_nb(fname)
should be changed to 
 nb = nbdev.maker.read_nb(fname)

and then  make a 'clean' subdirectory. import clean.py  in jupyter notebook and run proc_all() when in root directory of repository.
