### ISSUE TITLE
Lesson 1, Step 3 potentially uses photo from training set 

### ISSUE THREAD

**Issue by thiagohirai** [fastai/course22#28]
Given that we obtain bird.jpg from `search_images('bird photos', max_size=1)` and we obtain the training set from `search_images('bird photo')` it's possible that bird.jpg will be used in the training set (depending on whether duckduckgo returns it both times and on the 80% probability of this having been chosen for the training set).

It would be more better to use a completely new picture to evaluate our model's performance.

**Comment by jph00** [comment]
Yes it's possible - it's a good exercise to think about how best to check for that.
