### ISSUE TITLE
AttributeError: Custom classes or functions exported with your `Learner` not available in namespace.\Re-declare/import before loading: 	Can't get attribute 'Resampling' on <module 'PIL.Image' from 'C:\\Users\\Segun\\anaconda3\\lib\\site-packages\\PIL\\Image.py'>

### ISSUE THREAD

**Issue by segadeds** [fastai/course22#29]
learn_inf = load_learner('model.pkl')

I can import the pickle file I trained on Kaggle notebook on my jupyter notebook

**Comment by J-Savage** [comment]
I'm having the exact same issue. Training a model using GPU on Kaggle notebook, save the model, download it into local Jupyter notebook and get this error. 

I updated/downgraded PIL to version 9.3.0 to match the Kaggle version, restarted the kernel and it seems to work now.
