### ISSUE TITLE
Grammatical error on https://course.fast.ai/Lessons/part2.html

### ISSUE THREAD

**Issue by ConstantineK** [fastai/course22#69]
> Throughout the course, **we’ll PyTorch** to implement our models, and will create our own deep learning framework called miniai. 

Probably want to replace this with "we'll use PyTorch" or some other verb.

**Comment by yoavf** [comment]
This has been fixed in https://github.com/fastai/course22-web/pull/5

**Comment by ConstantineK** [comment]
then I will close this!
